### PR TITLE
fix(parser): allow '>' in attribute values

### PR DESCRIPTION
**Pull request by LukasHechenberger**

### CODE REVIEW

**Comment by LukasHechenberger** [comment]
Don't know how you run the tests locally, but i had to transform the `./test/test.js` file in order to run them.

```diff
diff --git a/test/test.js b/test/test.js
index e042534..09ea2da 100644
--- a/test/test.js
+++ b/test/test.js
@@ -22,7 +22,7 @@ module.exports.default = function(op) {
 });
 
 
-function test(options) {
+export default function test(options) {
   var parser = options.parser;
   var error = false;
   var expectedEntries = options.expect;
@@ -167,4 +167,4 @@ function test(options) {
 
 function indent(text, str) {
   return str + text.split(/\n/g).join('\n' + str);
-}
\ No newline at end of file
+}
```

**Comment by nikku** [comment]
Use `npm run all` to test, bundle and lint the project.

**Comment by LukasHechenberger** [comment]
Tried that, travis fails running it as well

**Comment by nikku** [comment]
Thanks for the heads up. Seems like the absence of a `package-lock` and some non-semver breaking change in `esm` made it fail, over time.

I've pulled in your fix.

**Comment by nikku** [comment]
Incorporated via https://github.com/nikku/saxen/pull/20.

**Pull request closed without merging**
